name: Book Catalog API Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install requirements.txt
        run: python -m pip install -r requirements.txt


      - name: build docker
        run: docker build -t book-catalog-app -f dockerfile .
